import type {Metadata} from "next";
import "./globals.css";
import 'swiper/css';
import 'swiper/css';
import 'swiper/css/autoplay'
import React from "react";
import {fairPlayFont} from "@/constants/fonts";
import {ContactForm, Footer, Header, MainContainer} from "@/components/layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={` ${fairPlayFont.className}  antialiased`}
        >
        <MainContainer>
            <Header/>
            {children}
                <ContactForm/>
            <Footer/>
        </MainContainer>
        </body>
        </html>
    );
}

