import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";
import {poppins} from "@/components/Fonts";




export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${poppins.className} bg-[#ededed]  antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
