import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import "swiper/css";
import "swiper/css/autoplay";
import 'swiper/css/pagination';
import React from "react";
import { fairPlayFont } from "@/constants/fonts";
import { ContactForm, MainContainer } from "@/components/layout";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` `}>
        <Theme>
          <MainContainer
            className={`${fairPlayFont.className}  min-h-screen flex flex-col justify-between `}
          >
            <Header />
            {children}
            <ContactForm />
            {/* <Footer /> */}
          </MainContainer>
        </Theme>
      </body>
    </html>
  );
}
